#!/usr/bin/env ruby
#
# This script connects to IB API, subscribes to account info and prints out
# messages received from IB (update every 3 minute or so)

require 'bundler/setup'
require 'logger'
require 'yaml'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'ib-ruby'

# Set log level
log.level = Logger::DEBUG #FATAL
include IB
# Connect to IB TWS
ib = Connection.new :client_id => 1113, :port => 4002 #,, :port => 7496 # TWS

# Only for Advisor accounts: you need to provide account_code such as U666777
account_code = ARGV[0] || ''

# Subscribe to TWS alerts/errors and account-related messages
# that TWS sends in response to account data request
ib.subscribe(:Alert, :AccountValue,
             :PortfolioValue, :AccountUpdateTime) { |msg| puts msg.to_human }

ib.send_message :RequestAccountData, :subscribe => true, :account_code => account_code

puts "\nSubscribing to IB account data"
puts "\n******** Press <Enter> to cancel... *********\n\n"
STDIN.gets
puts "Cancelling account data subscription.."

ib.send_message :RequestAccountData, :subscribe => false
sleep 2
