#!/usr/bin/env ruby
#
# This script connects to IB API and subscribes to Position Values which are updated regulary.
#

require 'bundler/setup'
require 'ib-ruby'
require_relative 'config_ib'

ib = IB::Connection.new client_id: 1111, host: $host, port: $port do |gw|
	## Subcribe to forseable events before the connection is completed
	## Subscribe to TWS alerts/errors
	gw.logger.level = Logger::FATAL # DEBUG INFO WARN ERROR FATAL
	gw.subscribe(:Alert, :PositionData) { |msg| puts msg.to_human }
end

Thread.new do
	sleep 3
	puts "\n******** Press <Enter> to quit *********\n\n"
end
# request the AccountSummary
ib.send_message :RequestPositions
STDIN.gets
puts "\n *** canceling Request ..."
ib.send_message :CancelPositions
sleep 1
puts "done."
