#!/usr/bin/env ruby
#
# This script allows you to cancel either a set of open Orders by their ids,
# or ALL Orders opened via IB API at once. The latter is useful when your
# robot goes crazy and opens gazillions of wrong limit orders.

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'ib-ruby'

# First, connect to IB TWS.
IB::Gateway.new  :port => 7496, :connect=> true , :client_id => 998 # TWS

if ( ib = IB::Gateway.tws).present?
  # Subscribe to TWS alerts/errors and order-related messages
  ib.subscribe( :OpenOrder, :OrderStatus, :OpenOrderEnd ) { |msg| puts msg.to_human }

  if ARGV.empty?
    ib.send_message :RequestGlobalCancel
  else
    # Will only work for Orders placed under the same :client_id
    ib.cancel_order *ARGV
  end

  ib.send_message :RequestAllOpenOrders

  sleep 3

else
  puts "Not Connected"
end
