#!/usr/bin/env ruby
#
# This script gets details for specific contract from IB

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'yaml'
require 'ib-ruby'

# Definition of what we want market data for.  We have to keep track of what ticker id
# corresponds to what symbol ourselves, because the ticks don't include any other
# identifying information. The choice of ticker ids is, as far as I can tell, arbitrary.
begin
@market = {0 => IB::Symbols::Stocks[:wfc],
           1 => IB::Symbols::Stocks[:vxx],
           2 => IB::Symbols::Futures[:vix],
           3 => IB::Symbols::Futures[:es],
           4 => IB::Symbols::Options[:wfc20],
	   5 => IB::Symbols::Options[:spy75],
           7 => IB::Symbols::Forex[:eurusd],
#           8 => IB::Symbols::Bonds[:wag],  --> bonds are not defined in contract_config (yet)
           9 => IB::Symbols::Stocks[:wrong] ,
           6 => IB::Symbols::Options[:vxx40] }  #--> osi definition is not supported

# Connect to IB TWS.
ib = IB::Connection.new :client_id => 1112, :port => 7496 # TWS

@market.each_pair do |id, contract|
  puts "\nRequesting contract data #{id}: #{contract.description}"
  puts contract.read_contract_from_tws
  puts contract.to_human
  # Request Contract details for the symbols we're interested in. TWS will
  # respond with ContractData messages, which will be processed by the code above.
end
rescue RuntimeError => e
	puts "Error"
	puts e
end

