#!/usr/bin/env ruby
#
# FLEX is a web-based service from IB that helps you to retrieve your activity,
# trades and positions. It is working independently from TWS or Gateway, using your
# internet connection directly. See /misc/flex for extended FLEX documentation.
#
# In order to use this service, activate it and configure your token first.
# Your Token is located at Account Management->Reports->Delivery Settings->Flex Web Service.
# You need to activate Flex Web Service and generate new token(s) there.
# Your Flex Query Ids are in Account Management->Reports->Activity->Flex Queries.
# Create new Flex query and make sure to set its output format to XML.
#
# This script runs your pre-defined FLEX query and prints the resulting report.

require 'bundler/setup'
require 'ib-ruby'
require 'yaml'
#### deactivated for now
#if File.exists? "config/flex.yml"
#  # You may want to put your favorite FLEX queries info into a separate yaml file, such as:
#  # -------------config/flex.yml---------------
#  # last_orders:
#  #   :token: 1111111111111111111111111111111111
#  #   :query_id: 79999
#  #   :format: :csv
#  # --------------------------------------------
#  #
#  query_name = ARGV[0] || 'default'
#  query = YAML::load_file('config/flex.yml')[query_name]
#  raise "FLEX error: no query #{query_name} in 'config/flex.yml'" unless query
#  raise "FLEX error: no token/query_id for #{query_name}" unless query[:token] && query[:query_id]
#else
#end

# Initiate FLEX request at a known FLEX Web Service URI
pp IB::Flex.new( token: , # 1111111111111111111111111111111111, # CHANGE to your actual token!
						    query_id: ARGV[0] || 328761, # CHANGE to actual query id!
							  verbose: true,
								return_hash: 1,
						    format: :xml ).run


