#!/usr/bin/env ruby
#
# This script downloads Fundamental data for specific symbols from IB
# This only works IF you have Reuters data subscription!

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'ib-ruby'
require 'xmlsimple'
require 'pp'

IB::Gateway.new  connect:true, host: 'beta:7496'
if ( ib = IB::Gateway.tws).present? 
  ib.subscribe(:Alert) { |msg| puts msg.to_human }

  # Fundamental Data will arrive in XML format, we need to parse it
  ib.subscribe(:FundamentalData) { |msg| @xml = XmlSimple.xml_in(msg.xml, :ForceArray => false) }

  ibm = IB::Stock.new  :symbol => 'IBM'
  ibm.update_contract

  # Request Fundamental Data for IBM. Possible report types:
  #     'estimates' - Estimates
  #     'finstat'   - Financial statements
  #     'snapshot' - Summary
  ib.send_message :RequestFundamentalData,
    :id => 10,
    :contract => ibm,
    :report_type => 'snapshot'

  # Needs some time to receive and parse XML. Standard timeout of 1 sec is just too low.
  ib.wait_for(30) { @xml}

  # Now just extract and use all the fundamental data you needed
  pp @xml
else
  puts "No TWS!"
end
