#!/usr/bin/env ruby
#
# This script downloads Fundamental data for specific symbols from IB
# This only works IF you have Reuters data subscription!

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require 'ib-ruby'
require 'xmlsimple'
require 'pp'

ib = IB::Connection.new :client_id => 1112 #, :port => 7496 # TWS

ib.subscribe(:Alert) { |msg| puts msg.to_human }

# Fundamental Data will arrive in XML format, we need to parse it
ib.subscribe(:FundamentalData) { |msg| @xml = XmlSimple.xml_in(msg.data, :ForceArray => false) }

ibm = IB::Contract.new :symbol => 'IBM',
                       :exchange => 'NYSE',
                       :currency => 'USD',
                       :sec_type => 'STK'

# Request Fundamental Data for IBM. Possible report types:
#     'estimates' - Estimates
#     'finstat'   - Financial statements
#     'snapshot' - Summary
ib.send_message :RequestFundamentalData,
                :id => 10,
                :contract => ibm,
                :report_type => 'snapshot'

# Needs some time to receive and parse XML. Standard timeout of 1 sec is just too low.
ib.wait_for(30) { @xml}

# Now just extract and use all the fundamental data you needed
pp @xml
