#!/usr/bin/env ruby
#
# This script retrieves list of all Orders from TWS

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'ib-ruby'

# Connect to IB as 0 (TWS) to retrieve all Orders, including TWS-generated ones
ib = IB::Connection.new :client_id => 0 #, :port => 7496 # TWS

# Subscribe to TWS alerts/errors and order-related messages
@counter = 0

ib.subscribe(:Alert, :OrderStatus, :OpenOrderEnd) { |msg| puts msg.to_human }

ib.subscribe(:OpenOrder) do |msg|
  @counter += 1
  puts "#{@counter}: #{msg.to_human}"
  #pp msg.order
end

ib.send_message :RequestAllOpenOrders

# Wait for IB to respond to our request
ib.wait_for :OpenOrderEnd
sleep 1 # Let printer do the job
