#!/usr/bin/env ruby

# This script reproduces https://github.com/ib-ruby/ib-ruby/issues/12

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'ib-ruby'

contract = IB::Contract.new :symbol=> 'AAPL',
                            :exchange=> "Smart",
                            :currency=> "USD",
                            :sec_type=> :stock,
                            :description=> "Some stock"

# First, connect to IB Gateway.
ib = IB::Connection.new :client_id => 1112, #  Arbitrary id to identify your script
                        #:port => 7496,     # TWS connection (instead of default Gateway)
                        :received => false  # Do not keep all received messages in memory

ib.subscribe(:Alert) { |msg| puts msg.to_human }
ib.subscribe(:TickGeneric, :TickString, :TickPrice, :TickSize) { |msg| puts msg.inspect }
ib.send_message :RequestMarketData, :id => 123, :contract => contract

puts "\nSubscribed to market data"
puts "\n******** Press <Enter> to cancel... *********\n\n"
gets
puts "Cancelling market data subscription.."
