require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Ib::ExecutionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ib::Execution. As you add validations to Ib::Execution, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:account_name => "DU111110",
     :client_id => 1111,
     :exchange => "IDEALPRO",
     :exec_id => "0001f4e8.4f5d48f1.01.01",
     :liquidation => true,
     :local_id => 373,
     :perm_id => 1695693619,
     :price => 1.31075,
     :average_price => 1.31075,
     :shares => 20000,
     :cumulative_quantity => 20000,
     :side => :buy,
     :time => "20120312  15:41:09",
     }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Ib::ExecutionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all executions as @executions" do
      execution = Ib::Execution.create! valid_attributes
      get :index, { :use_route => true}, valid_session
      assigns(:executions).should eq([execution])
    end
  end

  describe "GET show" do
    it "assigns the requested execution as @execution" do
      execution = Ib::Execution.create! valid_attributes
      get :show, {:id => execution.to_param, :use_route => true}, valid_session
      assigns(:execution).should eq(execution)
    end
  end

  describe "GET new" do
    it "assigns a new execution as @execution" do
      get :new, {:use_route => true}, valid_session
      assigns(:execution).should be_a_new(Ib::Execution)
    end
  end

  describe "GET edit" do
    it "assigns the requested execution as @execution" do
      execution = Ib::Execution.create! valid_attributes
      get :edit, {:id => execution.to_param, :use_route => true}, valid_session
      assigns(:execution).should eq(execution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ib::Execution" do
        expect {
          post :create, {:execution => valid_attributes, :use_route => true}, valid_session
        }.to change(Ib::Execution, :count).by(1)
      end

      it "assigns a newly created execution as @execution" do
        post :create, {:execution => valid_attributes, :use_route => true}, valid_session
        assigns(:execution).should be_a(Ib::Execution)
        assigns(:execution).should be_persisted
      end

      it "redirects to the created execution" do
        post :create, {:execution => valid_attributes, :use_route => true}, valid_session
        response.should redirect_to(Ib::Execution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved execution as @execution" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Execution.any_instance.stub(:save).and_return(false)
        post :create, {:execution => {}, :use_route => true}, valid_session
        assigns(:execution).should be_a_new(Ib::Execution)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Execution.any_instance.stub(:save).and_return(false)
        post :create, {:execution => {}, :use_route => true}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested execution" do
        execution = Ib::Execution.create! valid_attributes
        # Assuming there are no other executions in the database, this
        # specifies that the Ib::Execution created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ib::Execution.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => execution.to_param,
                      :execution => {'these' => 'params'},
                      :use_route => true}, valid_session
      end

      it "assigns the requested execution as @execution" do
        execution = Ib::Execution.create! valid_attributes
        put :update, {:id => execution.to_param,
                      :execution => valid_attributes,
                      :use_route => true}, valid_session
        assigns(:execution).should eq(execution)
      end

      it "redirects to the execution" do
        execution = Ib::Execution.create! valid_attributes
        put :update, {:id => execution.to_param,
                      :execution => valid_attributes,
                      :use_route => true}, valid_session
        response.should redirect_to(execution)
      end
    end

    describe "with invalid params" do
      it "assigns the execution as @execution" do
        execution = Ib::Execution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Execution.any_instance.stub(:save).and_return(false)
        put :update, {:id => execution.to_param,
                      :execution => {},
                      :use_route => true}, valid_session
        assigns(:execution).should eq(execution)
      end

      it "re-renders the 'edit' template" do
        execution = Ib::Execution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Execution.any_instance.stub(:save).and_return(false)
        put :update, {:id => execution.to_param,
                      :execution => {},
                      :use_route => true}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested execution" do
      execution = Ib::Execution.create! valid_attributes
      expect {
        delete :destroy, {:id => execution.to_param, :use_route => true}, valid_session
      }.to change(Ib::Execution, :count).by(-1)
    end

    it "redirects to the executions list" do
      pending 'Something is wrong with RSpecs redirect_to matcher'
      execution = Ib::Execution.create! valid_attributes
      delete :destroy, {:id => execution.to_param, :use_route => true}, valid_session
      response.should redirect_to(executions_url)
    end
  end

end
