# DB configuration file

# Test stand configurations (JRuby)
test: &test
  :adapter:     jdbcsqlite3
  :database:    db/test.sqlite3
  :pool:        5
  :timeout:     5000

# Test stand configurations (MRI)
test-mri:
  <<: *test
  :adapter:     sqlite3

# Battle configurations (JRuby)
prod:
  <<: *test
  :database:      db/prod.sqlite3

