require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Ib::UnderlyingsController, :type => :controller  do

  # This should return the minimal set of attributes required to create a valid
  # Underlying. As you add validations to Underlying, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:delta => 1.0, :price => 13.5}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UnderlyingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all underlyings as @underlyings" do
      underlying = Ib::Underlying.create! valid_attributes
      get :index, { :use_route => true}, valid_session
      assigns(:underlyings).should eq([underlying])
    end
  end

  describe "GET show" do
    it "assigns the requested underlying as @underlying" do
      underlying = Ib::Underlying.create! valid_attributes
      get :show, {:id => underlying.to_param, :use_route => true}, valid_session
      assigns(:underlying).should eq(underlying)
    end
  end

  describe "GET new" do
    it "assigns a new underlying as @underlying" do
      get :new, {:use_route => true}, valid_session
      assigns(:underlying).should be_a_new(Ib::Underlying)
    end
  end

  describe "GET edit" do
    it "assigns the requested underlying as @underlying" do
      underlying = Ib::Underlying.create! valid_attributes
      get :edit, {:id => underlying.to_param, :use_route => true}, valid_session
      assigns(:underlying).should eq(underlying)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Underlying" do
        expect {
          post :create, {:underlying => valid_attributes, :use_route => true}, valid_session
        }.to change(Ib::Underlying, :count).by(1)
      end

      it "assigns a newly created underlying as @underlying" do
        post :create, {:underlying => valid_attributes, :use_route => true}, valid_session
        assigns(:underlying).should be_a(Ib::Underlying)
        assigns(:underlying).should be_persisted
      end

      it "redirects to the created underlying" do
        post :create, {:underlying => valid_attributes, :use_route => true}, valid_session
        response.should redirect_to(Ib::Underlying.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved underlying as @underlying" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Underlying.any_instance.stub(:save).and_return(false)
        post :create, {:underlying => {}, :use_route => true}, valid_session
        assigns(:underlying).should be_a_new(Ib::Underlying)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Underlying.any_instance.stub(:save).and_return(false)
        post :create, {:underlying => {}, :use_route => true}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested underlying" do
        underlying = Ib::Underlying.create! valid_attributes
        # Assuming there are no other underlyings in the database, this
        # specifies that the Underlying created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ib::Underlying.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => underlying.to_param, :use_route => true,
                      :underlying => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested underlying as @underlying" do
        underlying = Ib::Underlying.create! valid_attributes
        put :update, {:id => underlying.to_param, :use_route => true,
                      :underlying => valid_attributes}, valid_session
        assigns(:underlying).should eq(underlying)
      end

      it "redirects to the underlying" do
        underlying = Ib::Underlying.create! valid_attributes
        put :update, {:id => underlying.to_param, :use_route => true,
                      :underlying => valid_attributes}, valid_session
        response.should redirect_to(underlying)
      end
    end

    describe "with invalid params" do
      it "assigns the underlying as @underlying" do
        underlying = Ib::Underlying.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Underlying.any_instance.stub(:save).and_return(false)
        put :update, {:id => underlying.to_param, :use_route => true,
                      :underlying => {}}, valid_session
        assigns(:underlying).should eq(underlying)
      end

      it "re-renders the 'edit' template" do
        underlying = Ib::Underlying.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ib::Underlying.any_instance.stub(:save).and_return(false)
        put :update, {:id => underlying.to_param, :use_route => true,
                      :underlying => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested underlying" do
      underlying = Ib::Underlying.create! valid_attributes
      expect {
        delete :destroy, {:id => underlying.to_param, :use_route => true}, valid_session
      }.to change(Ib::Underlying, :count).by(-1)
    end

    it "redirects to the underlyings list" do
      pending 'Something is wrong with RSpecs redirect_to matcher'
      underlying = Ib::Underlying.create! valid_attributes
      delete :destroy, {:id => underlying.to_param, :use_route => true}, valid_session
      response.should redirect_to(underlyings_url) #, :host => 'test.host')#:only_path => true)
    end
  end

end
